### ISSUE TITLE
l1t does not compile on macOS

### ISSUE THREAD

**Issue by alex-laycalvert** [alex-laycalvert/l1t#4]
**Describe the bug**
Running `make` or `make dev` produces compiler errors related to uses of `menu.h` functions in `l1t`.

**Screenshots**
<img width="702" alt="Screen Shot 2022-10-07 at 11 54 22 PM" src="https://user-images.githubusercontent.com/45835678/194687001-121bf3fe-a2b3-4e5a-9ea2-7067f0d3bf13.png">

**Operating System**
macOS 12.4

**Comment by alex-laycalvert** [comment]
Updated to macOS 12.6, same issue

**Comment by ayaan-qadri** [comment]
it may help:

https://stackoverflow.com/questions/3703792/ld-symbols-not-found-when-linking
